# Generated by Django 4.1.5 on 2023-01-12 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_is_good"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="edit_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, help_text="fecha de modificación"
            ),
        ),
    ]
